### PR TITLE
Add installing instructions using package managers to README

### PR DESCRIPTION
**Pull request by eunos-1128**
Dear,

Thank you for your excellent work. 

I added brew and conda installation instructions.

I know that they are not official methods, but they are useful for users who want to manage USalign using package managers.

- https://github.com/brewsci/homebrew-bio/blob/develop/Formula/usalign.rb
- https://anaconda.org/bioconda/usalign

Regards,

### CODE REVIEW

**Comment by kad-ecoli** [comment]
Do you mind adding conda support for win64? US-align is known to compile by g++ in mingw-w64, either natively on Windows 64 or cross-compiling on Linux?

**Comment by kad-ecoli** [comment]
If that is not possible, you should be clear on what OS the conda package supports.

**Comment by kad-ecoli** [comment]
For linux-64, win-64 and linux-aarch64, I suggest compiling with ``-static`` to avoid dependency on specific glibc version.

**Comment by eunos-1128** [comment]
@kad-ecoli
> Do you mind adding conda support for win64? US-align is known to compile by g++ in mingw-w64, either natively on Windows 64 or cross-compiling on Linux?

By default bioconda doesn't handle native win-64 build, although the compilation is usually achieved by g++ in mingw-w64.

I added notes on that.

**Comment by eunos-1128** [comment]
@kad-ecoli 

> For linux-64, win-64 and linux-aarch64, I suggest compiling with `-static` to avoid dependency on specific glibc version.

This is the current build script used in the bioconda.
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/usalign/build.sh

I'll revise the script to use `-static`.

Thank you for your advice:)

**Comment by kad-ecoli** [comment]
Manually merge your commits. Remove statement on conda supporting win-64 until you have added corresponding support.

**Comment by eunos-1128** [comment]
@kad-ecoli 
Thank you!

**Pull request closed without merging**
